const ADD_TODO = 'ADD_TODO';
const GET_TODOS = 'GET_TODOS';
const DELETE_TODO = 'DELETE_TODO';
const UPDATE_CURRENT_TODO_TEXT = 'UPDATE_CURRENT_TODO_TEXT';
const TOGGLE_UPDATE_TODO_MODAL = 'TOGGLE_UPDATE_TODO_MODAL';
const UPDATE_CURRENT_TODO_ID = 'UPDATE_CURRENT_TODO_ID';
const UPDATE_MODIFIED_TEXT = 'UPDATE_MODIFIED_TEXT';
const UPDATE_TODO = 'UPDATE_TODO';

export {
    GET_TODOS,
    ADD_TODO,
    DELETE_TODO,
    UPDATE_CURRENT_TODO_TEXT,
    TOGGLE_UPDATE_TODO_MODAL,
    UPDATE_CURRENT_TODO_ID,
    UPDATE_MODIFIED_TEXT,
    UPDATE_TODO
}